# Generated by Django 5.2.4 on 2025-08-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0005_remove_notification_comment_remove_like_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
