# Generated by Django 5.1.6 on 2025-08-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0006_remove_chatmessage_chat_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
